INSERT INTO user(USER_ID, EMAIL, PASSWORD, ACTIVATED) VALUES (1, 'admin@gmail.com', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1);
INSERT INTO user(USER_ID, EMAIL, PASSWORD, ACTIVATED) VALUES (2, 'user@gmail.com', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1);

INSERT INTO authority(AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO authority(AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO user_authority(USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO user_authority(USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO user_authority(USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');